use_frameworks!

target 'KRAnimation_Example' do
  pod 'KRAnimation', :path => '../'

  pod 'KRTimingFunction', :git => 'https://github.com/BridgeTheGap/KRTimingFunction.git', :submodules => true

  # target 'KRAnimation_Tests' do
  #   inherit! :search_paths

    
  # end
end
